name: py-winrm-plugin
rundeckPluginVersion: 1.2
author: "@author@"
date: "@date@"
version: "@version@"
url: "@url@"
providers:
  - name: WinRMPython
    title: WinRM Node Executor Python
    description: Executing Scripts or Commands on remote Windows computer
    service: NodeExecutor
    plugin-type: script
    script-interpreter: python -u
    script-file: winrm-exec.py
    script-args: ${node.hostname}
    config:
      - name: authtype
        title: Authentication Type
        description: "Authentication Type"
        type: Select
        values: "basic,credssp,ntlm,kerberos"
        default: "basic"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Authentication
          instance-scope-node-attribute: "winrm-authtype"
      - name: nossl
        title: No SSL Verification
        description: "When set to true ssl certificate validation is not performed"
        type: Select
        values: "true, false"
        default: "false"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-nossl"
      - name: disabletls12
        title: Disable TLS 1.2
        description: "Disable TLS 1.2 in order to run over TLS 1.0"
        type: Boolean
        default: "false"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-disable-tls-12"
      - name: winrmtransport
        title: WinRM Transport Protocol
        description: "WinRM transport protocol (http or https)"
        type: Select
        default: "http"
        values: "http, https"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-transport"
      - name: winrmport
        title: WinRM Port
        description: "WinRM port (Default: 5985/5986 for http/https)"
        type: String
        default: "5985"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-port"
      - name: certpath
        title: Certificate Path
        description: "Certificate path for ssl verification"
        type: String
        required: false
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-certpath"
      - name: shell
        title: Shell
        description: "Windows Shell interpreter"
        type: Select
        values: "cmd, powershell"
        default: 'powershell'
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-shell"
      - name: username
        title: Username
        type: String
        required: false
        description: "Optional username. The username can be set at node level (using the attribute `username`) or at job level (using an input option called `username`)."
        scope: Instance
        renderingOptions:
          groupName: Authentication
      - name: password_storage_path
        title: Password Storage Path
        type: String
        required: false
        description: "Optional storage password path. Can contain property references to node attributes. A node attribute named winrm-password-storage-path will override this value."
        scope: Instance
        renderingOptions:
          groupName: Authentication
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
          instance-scope-node-attribute: "winrm-password-storage-path"
      - name: krb5config
        title: krb5 Config File
        description: "Path of krb5.conf file"
        type: String
        default: '/etc/krb5.conf'
        required: false
        renderingOptions:
          groupName: Kerberos
      - name: kinit
        title: Kinit Command
        description: "Kinit Command"
        type: String
        default: 'kinit'
        required: false
        renderingOptions:
          groupName: Kerberos
  - name: WinRMcpPython
    title: WinRM Python File Copier
    description: Copying files to remote Windows computer
    service: FileCopier
    plugin-type: script
    script-interpreter: python -u
    script-file: winrm-filecopier.py
    script-args: ${node.hostname} ${file-copy.file} ${file-copy.destination}
    config:
      - name: authtype
        title: Authentication Type
        description: "Authentication Type"
        type: Select
        values: "basic,credssp,ntlm,kerberos"
        default: "basic"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Authentication
          instance-scope-node-attribute: "winrm-authtype"
      - name: nossl
        title: No SSL Verification
        description: "When set to true ssl certificate validation is not performed"
        type: Select
        values: "true, false"
        default: "false"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-nossl"
      - name: disabletls12
        title: Disable TLS 1.2
        description: "Disable TLS 1.2 in order to run over TLS 1.0"
        type: Boolean
        default: "false"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-disable-tls-12"
      - name: winrmtransport
        title: WinRM Transport Protocol
        description: "WinRM transport protocol (Default: http or https when ssl is selected for Authentication type)"
        type: Select
        default: "http"
        values: "http, https"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-transport"
      - name: winrmport
        title: WinRM Port
        description: "WinRM port (Default: 5985/5986 for http/https)"
        type: String
        default: "5985"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-port"
      - name: certpath
        title: Certificate Path
        description: "Certificate path for ssl verification"
        type: String
        required: false
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-certpath"
      - name: username
        title: Username
        type: String
        required: false
        description: "Optional username. The username can be set at node level (using the attribute `username`) or at job level (using an input option called `username`)."
        scope: Instance
        renderingOptions:
          groupName: Authentication
      - name: password_storage_path
        title: Password Storage Path
        type: String
        required: false
        description: "Optional storage password path. Can contain property references to node attributes. A node attribute named winrm-password-storage-path will override this value."
        scope: Instance
        renderingOptions:
          groupName: Authentication
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
          instance-scope-node-attribute: "winrm-password-storage-path"
      - type: Boolean
        name: debug
        title: Debug?
        description: 'Write debug messages'
      - name: krb5config
        title: krb5 Config File
        description: "Path of krb5.conf file"
        type: String
        default: '/etc/krb5.conf'
        required: false
        renderingOptions:
          groupName: Kerberos
      - name: kinit
        title: Kinit Command
        description: "Kinit Command"
        type: String
        default: 'kinit'
        required: false
        renderingOptions:
          groupName: Kerberos
  - name: WinRMCheck
    title: WinRM Check Step
    description: Check the connection with a remote node using winrm-python
    service: WorkflowStep
    plugin-type: script
    script-interpreter: python -u
    script-args: "--username ${config.username} --hostname ${config.hostname} --password ${config.password_storage_path} --authentication ${config.authtype} --transport ${config.winrmtransport} --port ${config.winrmport} --nossl ${config.nossl} --debug ${config.debug} --certpath ${config.certpath}"
    script-file: winrm-check.py
    config:
      - name: hostname
        title: Hostname
        description: "Window's Hostname"
        type: String
        required: true
      - name: authtype
        title: Authentication Type
        description: "Authentication Type"
        type: Select
        values: "basic,credssp,ntlm,kerberos"
        default: "basic"
        required: true
      - name: winrmtransport
        title: WinRM Transport Protocol
        description: "WinRM transport protocol (http or https)"
        type: Select
        default: "http"
        values: "http, https"
        required: true
        scope: Instance
      - name: nossl
        title: No SSL Verification
        description: "When set to true ssl certificate validation is not performed"
        type: Select
        values: "true, false"
        default: "false"
        required: true
      - name: disabletls12
        title: Disable TLS 1.2
        description: "Disable TLS 1.2 in order to run over TLS 1.0"
        type: Boolean
        default: "false"
        required: true
      - name: winrmport
        title: WinRM Port
        description: "WinRM port (Default: 5985/5986 for http/https)"
        type: String
        default: "5985"
        required: true
      - name: certpath
        title: Certificate Path
        description: "Certificate path for ssl verification"
        type: String
        required: false
      - name: username
        title: Username
        description: "Username from window box"
        type: String
        required: true
      - name: password_storage_path
        title: Password Storage Path
        type: String
        required: true
        description: "Password storage password path."
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: Boolean
        name: debug
        title: Debug?
        description: 'Write debug messages'
      - name: krb5config
        title: krb5 Config File
        description: "Path of krb5.conf file"
        type: String
        default: '/etc/krb5.conf'
        required: false
        renderingOptions:
          groupName: Kerberos
      - name: kinit
        title: Kinit Command
        description: "Kinit Command"
        type: String
        default: 'kinit'
        required: false
        renderingOptions:
          groupName: Kerberos

